CREATE TABLE Sensor(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null unique
);

CREATE TABLE Measurement(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value double precision not null,
    raining boolean not null,
    measurement_date_time timestamp not null,
    sensor varchar(100) references Sensor(name)
);